name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-bun -f packages/ui/ct.dockerfile .

      - name: Run tests
        run: |
          docker run \
            -v $(pwd)/playwright-report:/app/playwright-report \
            -e CI=true \
            playwright-bun

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
