name: publish package

on:
  release:
    types: [released]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN_AUTOMATION: ${{ secrets.NPM_TOKEN_AUTOMATION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Verify token set in root
        run: |
          TOKEN_LINE=$(grep '_authToken' .npmrc)
          echo "${TOKEN_LINE:0:40}"

      - name: Verify token set in packages/react
        run: |
          TOKEN_LINE=$(grep '_authToken' packages/react/.npmrc)
          echo "${TOKEN_LINE:0:40}"

      - name: Verify NPM Authentication
        run: npm whoami

      - name: Install dependencies
        run: bun install

      - name: Build and Test
        run: bun run package
